accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profiles/<str:username>/', views.profile_view, name='view_profile'),
    path('profile/edit/', views.update_profile_view, name='edit_profile'),
    path('password/edit/', views.update_password_view, name='edit_password'),
    path('mydashboard/', views.user_dashboard_view, name='my_dashboard'),
]

mastercook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('shortcodes/', views.shortcodes)
]

"""
urlpatterns += i18n_patterns(
    path('generic/', include('generic.urls')),
    path('', include('recipes.urls')),
    path('accounts/', include('accounts.urls'))
)
"""

urlpatterns += [
    path('', views.root_redirect),
    path('utils/', include('utils.urls')),
    path('recipes/', include('recipes.urls')),
    path('accounts/', include('accounts.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.recipe_homepage, name='homepage'),
    path('create', views.recipe_create, name='create'),
    path('delete/<int:recipe_pk>', views.recipe_delete, name='delete'),
    path('<slug:recipe_slug>/edit', views.recipe_edit, name='edit'),
    path('<int:recipe_pk>/publish_toogle', views.recipe_toogle_publish, name='publish_toogle'),
    path('<int:recipe_pk>/comment/add', views.recipe_add_comment, name='add_comment'),
    path('<int:recipe_pk>/image/add', views.recipe_add_image, name='add_image'),
    path('image/delete/<int:image_pk>', views.recipe_delete_image, name='delete_image'),
    path('<int:recipe_pk>/step/add', views.recipe_add_step, name='add_step'),
    path('step/up/<int:step_pk>', views.recipe_up_step, name='up_step'),
    path('step/down/<int:step_pk>', views.recipe_down_step, name='down_step'),
    path('step/delete/<int:step_pk>', views.recipe_delete_step, name='delete_step'),
    path('<int:recipe_pk>/ingredient/add', views.recipe_add_ingredient, name='add_ingredient'),
    path('ingredient/delete/<int:ingredient_pk>', views.recipe_delete_ingredient, name='delete_ingredient'),
    path('<int:recipe_pk>/rate/add', views.recipe_add_rate, name='add_rate'),
    path('<slug:recipe_slug>/details', views.recipe_details, name='details'),
    path('comment/<int:comment_pk>/replyto', views.recipe_reply_comment, name='reply_to_comment'),
    path('search', views.recipe_search, name='search'),
    path('browse/all', views.recipe_browse_all, name='browse_all'),
    path('browse/category/<slug:category_slug>', views.recipe_browse_category, name='browse_category'),
    path('browse/skill/<slug:skill_slug>', views.recipe_browse_skill, name='browse_skill')
]

utils/urls.py
from django.urls import path
from . import views

app_name = 'utils'

urlpatterns = [
    path('changueLocale/<str:user_language>', views.switch_lang_view, name='switch_language'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from utils.models import Country

# Create your models here.


class CookerProfile(models.Model):
    """
    Model to represent a MasterCook website user
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    date_of_birth = models.DateField(null=True, blank=True)
    bio = models.TextField(max_length=1000, blank=True)
    avatar = models.ImageField(default='default/default_avatar.png', blank=True,
                               upload_to='images/avatars')
    country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True)

accounts/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from .models import CookerProfile
from utils.models import Country
from datetime import datetime


class CookerAuthenticationForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': _("Username"),
            'aria-describedby': 'sizing-addon1',
        }
    ), localize=True)
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': _("Password"),
            'aria-describedby': 'sizing-addon1',
        },
    ), localize=True)

    class Meta:
        model = User
        fields = (
            'username',
            'password'
        )


class CookerCreationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': _("Username"),
            'aria-describedby': 'sizing-addon1',
        }
    ), localize=True)
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': _("First Name"),
            'aria-describedby': 'sizing-addon1',
        }
    ), localize=True)
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': _("Last Name"),
            'aria-describedby': 'sizing-addon1',
        }
    ), localize=True)
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={
            'class': 'form-control',
            'placeholder': _("Email"),
            'aria-describedby': 'sizing-addon1',
        }
    ), localize=True)
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': _("Password"),
            'aria-describedby': 'sizing-addon1',
        }
    ), localize=True)
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': _("Re-enter your password"),
            'aria-describedby': 'sizing-addon1',
        }
    ), localize=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )


class UserEditForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': _("First Name"),
            'aria-describedby': 'sizing-addon1',
        }
    ), localize=True)
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': _("Last Name"),
            'aria-describedby': 'sizing-addon1',
        }
    ), localize=True)
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={
            'class': 'form-control',
            'placeholder': _("Email"),
            'aria-describedby': 'sizing-addon1',
        }
    ), localize=True)

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email'
        )


class CookerChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': _("Old Password"),
            'aria-describedby': 'sizing-addon1',
        },
    ), localize=True)
    new_password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': _("New Password"),
            'aria-describedby': 'sizing-addon1',
        },
    ), localize=True)
    new_password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': _("Re-enter the new password"),
            'aria-describedby': 'sizing-addon1',
        },
    ), localize=True)


class CookerProfileForm(forms.ModelForm):
    date_of_birth = forms.DateField(widget=forms.DateInput(
        attrs={
            'class': 'form-control',
            'type': 'date',
            'placeholder': _("Date of birth"),
            'aria-describedby': 'sizing-addon1',
        }
    ), localize=True)
    bio = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': _("Biography"),
            'aria-describedby': 'sizing-addon1',
        }
    ), localize=True)
    avatar = forms.ImageField(widget=forms.FileInput(
        attrs={
            'class': 'form-control',
            'aria-describedby': 'sizing-addon1',
        }
    ), required=False)
    country = forms.ModelChoiceField(widget=forms.Select(
        attrs={
            'class': 'form-control',
            'aria-describedby': 'sizing-addon1',
        }
    ), localize=True, queryset=Country.objects.all())

    def __init__(self, *args, **kwargs):
        super(CookerProfileForm, self).__init__(*args, **kwargs)
        if self.instance.date_of_birth is not None:
            self.initial["date_of_birth"] = datetime.strftime(self.instance.date_of_birth, "%Y-%m-%d")

    class Meta:
        model = CookerProfile
        fields = (
            'date_of_birth',
            'bio',
            'avatar',
            'country',
        )

accounts/views.py
from django.shortcuts import render, redirect
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import CookerAuthenticationForm, CookerCreationForm, CookerProfileForm, UserEditForm, \
    CookerChangePasswordForm
from .models import CookerProfile
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404


# Create your views here


def signup_view(request):
    """
    View to allow a user to sign up on the website
    :param request:
    :return:
    """
    if request.method == 'POST':
        form = CookerCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.profile = CookerProfile.objects.create(user=user)
            # log the user in
            login(request, user)
            return redirect('recipes:homepage')
    else:
        form = CookerCreationForm()
    return render(request, 'accounts/accounts_signup.html', {'form': form})


def login_view(request):
    """
    View to allow a user to login on the website
    :param request:
    :return:
    """
    if request.method == 'POST':
        form = CookerAuthenticationForm(data=request.POST)
        if form.is_valid():
            # log in the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('recipes:homepage')
    else:
        form = CookerAuthenticationForm()
    return render(request, 'accounts/accounts_login.html', {'form': form})


def logout_view(request):
    """
    View to allow a user to logout
    :param request:
    :return:
    """
    logout(request)
    return redirect('recipes:homepage')


def profile_view(request, username):
    """
    View to consult a user profile
    :param request:
    :param username: The username of the user with this profile
    :return:
    """
    user = get_object_or_404(User, username=username)
    if hasattr(user, 'profile') is False:
        user.profile = CookerProfile.objects.create(user=user)
        user.save()
    return render(request, 'accounts/accounts_profile_view.html', {'user': user})


@login_required(login_url='accounts:login')
def update_profile_view(request):
    """
    View to update profile informations for the current user
    :param request:
    :return:
    """
    if hasattr(request.user, 'profile') is False:
        request.user.profile = CookerProfile.objects.create(user=request.user)
        request.user.save()
    if request.method == 'POST':
        user_form = UserEditForm(request.POST, request.FILES, instance=request.user)
        profile_form = CookerProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, _('Profile saved successfully'))
        else:
            messages.error(request, _('Please correct the error'))
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = CookerProfileForm(instance=request.user.profile)
    return render(request, 'accounts/accounts_profile_edit.html',
                  {'user': request.user,
                   'user_form': user_form,
                   'profile_form': profile_form
                   })


@login_required(login_url='accounts:login')
def update_password_view(request):
    """
    View to update the password of the current user
    :param request:
    :return:
    """
    if request.method == 'POST':
        password_form = CookerChangePasswordForm(request.user, request.POST)
        if password_form.is_valid():
            user = password_form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, _('Your password was successfully updated!'))
            return redirect('accounts:edit_password')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        password_form = CookerChangePasswordForm(request.user)
    return render(request, 'accounts/accounts_password_edit.html', {
        'form': password_form
    })


@login_required(login_url='accounts:login')
def user_dashboard_view(request):
    """
    View to consult the dashboard of the current user
    :param request:
    :return:
    """
    recipes = request.user.recipes.all()
    rates = request.user.rates.all()
    return render(request, 'accounts/accounts_user_dashboard.html', {
        'recipes': recipes,
        'rates': rates,
    })

accounts/templates/accounts/parts/_view_profile.html
{% load i18n %}

<h1 class="title wow fadeInLeftBig animated" data-wow-duration="1000ms" data-wow-delay="300ms"
    style="visibility: visible; animation-duration: 1000ms; animation-delay: 300ms; animation-name: fadeInLeftBig;">
    {% trans "Profile of" %} : {{ user.username }}
</h1>
<img class="avatar" src="{{ user.profile.avatar.url }}" alt=""/>
<br><br>
<div class="input-group input-group-lg wow fadeInUp animated" data-wow-duration="1000ms"
     data-wow-delay="300ms"
     style="visibility: visible; animation-duration: 1000ms; animation-delay: 300ms; animation-name: fadeInUp;">
    <span class="input-group-addon" id="basic-addon1"><i class="fas fa-user-circle"></i></span>
    <input class="form-control" type="text" value="{{ user.first_name }}" disabled>
</div>
<div class="input-group input-group-lg wow fadeInUp animated" data-wow-duration="1000ms"
     data-wow-delay="300ms"
     style="visibility: visible; animation-duration: 1000ms; animation-delay: 300ms; animation-name: fadeInUp;">
    <span class="input-group-addon" id="basic-addon1"><i class="fas fa-user-circle"></i></span>
    <input class="form-control" type="text" value="{{ user.last_name }}" disabled>
</div>
<div class="input-group input-group-lg wow fadeInUp animated" data-wow-duration="1000ms"
     data-wow-delay="300ms"
     style="visibility: visible; animation-duration: 1000ms; animation-delay: 300ms; animation-name: fadeInUp;">
    <span class="input-group-addon" id="basic-addon1"><i class="fas fa-at"></i></span>
    <input class="form-control" type="text" value="{{ user.email }}" disabled>
</div>
<div class="input-group input-group-lg wow fadeInUp animated" data-wow-duration="1000ms"
     data-wow-delay="300ms"
     style="visibility: visible; animation-duration: 1000ms; animation-delay: 300ms; animation-name: fadeInUp;">
    <span class="input-group-addon" id="basic-addon1"><i class="fas fa-birthday-cake"></i></span>
    <input class="form-control" type="text" value="{{ user.profile.date_of_birth }}" disabled>
</div>
<div class="input-group input-group-lg wow fadeInUp animated" data-wow-duration="1000ms"
     data-wow-delay="300ms"
     style="visibility: visible; animation-duration: 1000ms; animation-delay: 300ms; animation-name: fadeInUp;">
    <span class="input-group-addon" id="basic-addon1"><i class="fas fa-address-book"></i></span>
    <textarea class="form-control" rows="4" cols="50" disabled>{{ user.profile.bio }}</textarea>
</div>
<div class="input-group input-group-lg wow fadeInUp animated" data-wow-duration="1000ms"
     data-wow-delay="300ms"
     style="visibility: visible; animation-duration: 1000ms; animation-delay: 300ms; animation-name: fadeInUp;">
    <span class="input-group-addon" id="basic-addon1"><i class="fas fa-globe-americas"></i></span>
    <input class="form-control" type="text" value="{{ user.profile.country }}" disabled>
</div>

accounts/templates/accounts/parts/_view_user_rates.html
{% load i18n %}

<h3 class="bars wow fadeInUp animated" data-wow-duration="1000ms" data-wow-delay="300ms"
    style="visibility: visible; animation-duration: 1000ms; animation-delay: 300ms; animation-name: fadeInUp;">
    {% trans "My Latest Ratings" %}</h3>
<button class="btn btn-default btn-lg" data-toggle="collapse"
        data-target="#div_rates">{% trans "Show My Latest Rates" %}</button>
<div id="div_rates" class="collapse">
    {% if rates.count > 0 %}
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th style="width:10%">{% trans "Thumbnail" %}</th>
                <th>{% trans "Title" %}</th>
                <th>{% trans "Rates" %}</th>
                <th>{% trans "Median Rate" %}</th>
                <th>{% trans "My Rate" %}</th>
                <th>{% trans "Rated On" %}</th>
            </tr>
            </thead>
            <tbody>
            {% for rate in rates %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><img src="{{ rate.recipe.thumbnail.url }}" class="img-responsive" alt=""/></td>
                    <td><a href="{% url 'recipes:details' recipe_slug=rate.recipe.slug %}">{{ rate.recipe.name }}</a>
                    </td>
                    <td><span class="badge badge-warning">{{ rate.recipe.rates.count }}</span></td>
                    <td>
                        <input type="text"
                               value="{{ rate.recipe.get_median_rate }}"
                               data-size="xs"
                               class="rating-disabled">
                    </td>
                    <td>
                        <form action="{% url 'recipes:add_rate' recipe_pk=rate.recipe.pk %}?next={% url 'accounts:my_dashboard' %}"
                              method="post">
                            {% csrf_token %}
                            <div style="display:inline-block">
                                {{ rate.get_form_rate.rate }}
                            </div>
                            <div style="display:inline-block">
                                <button type="submit" class="btn btn-default btn-xs">{% trans "Rate" %}</button>
                            </div>
                        </form>
                    </td>
                    <td>{{ rate.updated_at }}</td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <br>
        <div class="alert alert-info">
            <strong>{% trans "Sorry but you have not rated any recipes yet :(" %}</strong>
        </div>
    {% endif %}
</div>
<br><br>

accounts/templates/accounts/parts/_view_user_recipes.html
{% load i18n %}

<h3 class="bars wow fadeInUp animated" data-wow-duration="1000ms" data-wow-delay="300ms"
    style="visibility: visible; animation-duration: 1000ms; animation-delay: 300ms; animation-name: fadeInUp;">
    {% trans "My Recipes" %}</h3>
<button class="btn btn-default btn-lg" data-toggle="collapse"
        data-target="#div_images">{% trans "Show My Recipes" %}</button>
<div id="div_images" class="collapse">
    {% if recipes.count > 0 %}
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th style="width:10%">{% trans "Thumbnail" %}</th>
                <th>{% trans "Title" %}</th>
                <th>{% trans "Median Rate" %}</th>
                <th>{% trans "Comments" %}</th>
                <th>{% trans "Published" %} ?</th>
                <th>{% trans "Created On" %}</th>
                <th>{% trans "Updated On" %}</th>
                <th>{% trans "Actions" %}</th>
            </tr>
            </thead>
            <tbody>
            {% for recipe in recipes %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><img src="{{ recipe.thumbnail.url }}" class="img-responsive" alt=""/></td>
                    <td>
                        {% if recipe.published %}
                            <a href="{% url 'recipes:details' recipe_slug=recipe.slug %}">{{ recipe.name }}</a>
                        {% else %}
                            {{ recipe.name }}
                        {% endif %}
                    </td>
                    <td><span class="badge badge-success">{{ recipe.get_median_rate }}</span></td>
                    <td><span class="badge badge-warning">{{ recipe.comments.count }}</span></td>
                    <td>
                        {% if recipe.published %}
                            <i class="fas fa-check-circle fa-lg" style="color:green"></i>
                        {% else %}
                            <i class="fas fa-exclamation-triangle fa-lg" style="color:orange"></i>
                        {% endif %}
                    </td>
                    <td>{{ recipe.created_at }}</td>
                    <td>{{ recipe.updated_at }}</td>
                    <td>
                        <a href="{% url 'recipes:edit' recipe_slug=recipe.slug %}"
                           class="btn btn-warning btn-sm">{% trans "Edit" %} <i class="fas fa-edit fa-lg"></i></a>
                        <button type="button" class="btn btn-danger btn-sm btn-confirm"
                                data-title="{% trans "Delete Recipe ?" %}"
                                data-message="{% trans "Are you sure that you want to delete this recipe ?" %}"
                                data-action="{% url 'recipes:delete' recipe_pk=recipe.pk %}?next={% url 'accounts:my_dashboard' %}">{% trans "Delete" %} <i
                                class="fas fa-trash-alt fa-lg"></i></button>
                        <br>
                        {% if recipe.published %}
                            <a href="{% url 'recipes:publish_toogle' recipe_pk=recipe.pk %}?next={% url 'accounts:my_dashboard' %}"
                               class="btn btn-default btn-sm" style="margin-top:5px;">
                                {% trans "Unpublish" %} <i class="fas fa-download"></i>
                            </a>
                        {% else %}
                            <a href="{% url 'recipes:publish_toogle' recipe_pk=recipe.pk %}?next={% url 'accounts:my_dashboard' %}"
                               class="btn btn-info btn-sm" style="margin-top:5px;">
                                {% trans "Publish" %} <i class="fas fa-upload"></i>
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <br>
        <div class="alert alert-info">
            <strong>{% trans "Sorry but you have no recipes yet :(" %}</strong>
        </div>
    {% endif %}
</div>
<br><br>