accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profiles/<str:username>/', views.profile_view, name='view_profile'),
    path('profile/edit/', views.update_profile_view, name='edit_profile'),
    path('password/edit/', views.update_password_view, name='edit_password'),
    path('mydashboard/', views.user_dashboard_view, name='my_dashboard'),
]

mastercook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('shortcodes/', views.shortcodes)
]

"""
urlpatterns += i18n_patterns(
    path('generic/', include('generic.urls')),
    path('', include('recipes.urls')),
    path('accounts/', include('accounts.urls'))
)
"""

urlpatterns += [
    path('', views.root_redirect),
    path('utils/', include('utils.urls')),
    path('recipes/', include('recipes.urls')),
    path('accounts/', include('accounts.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.recipe_homepage, name='homepage'),
    path('create', views.recipe_create, name='create'),
    path('delete/<int:recipe_pk>', views.recipe_delete, name='delete'),
    path('<slug:recipe_slug>/edit', views.recipe_edit, name='edit'),
    path('<int:recipe_pk>/publish_toogle', views.recipe_toogle_publish, name='publish_toogle'),
    path('<int:recipe_pk>/comment/add', views.recipe_add_comment, name='add_comment'),
    path('<int:recipe_pk>/image/add', views.recipe_add_image, name='add_image'),
    path('image/delete/<int:image_pk>', views.recipe_delete_image, name='delete_image'),
    path('<int:recipe_pk>/step/add', views.recipe_add_step, name='add_step'),
    path('step/up/<int:step_pk>', views.recipe_up_step, name='up_step'),
    path('step/down/<int:step_pk>', views.recipe_down_step, name='down_step'),
    path('step/delete/<int:step_pk>', views.recipe_delete_step, name='delete_step'),
    path('<int:recipe_pk>/ingredient/add', views.recipe_add_ingredient, name='add_ingredient'),
    path('ingredient/delete/<int:ingredient_pk>', views.recipe_delete_ingredient, name='delete_ingredient'),
    path('<int:recipe_pk>/rate/add', views.recipe_add_rate, name='add_rate'),
    path('<slug:recipe_slug>/details', views.recipe_details, name='details'),
    path('comment/<int:comment_pk>/replyto', views.recipe_reply_comment, name='reply_to_comment'),
    path('search', views.recipe_search, name='search'),
    path('browse/all', views.recipe_browse_all, name='browse_all'),
    path('browse/category/<slug:category_slug>', views.recipe_browse_category, name='browse_category'),
    path('browse/skill/<slug:skill_slug>', views.recipe_browse_skill, name='browse_skill')
]

utils/urls.py
from django.urls import path
from . import views

app_name = 'utils'

urlpatterns = [
    path('changueLocale/<str:user_language>', views.switch_lang_view, name='switch_language'),
]

recipes/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.utils.translation import ugettext_lazy as _
from .models import Recipe, RecipeType, RecipeSkill, RecipeComment, RecipeRate, RecipeIngredient, RecipeStep, \
    RecipeImage
from . import forms as recipeforms
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from slugify import slugify
from datetime import datetime
from django.core.paginator import Paginator
from django.conf import settings
from django.db.models import Avg, Q


# Create your views here.

def recipe_homepage(request):
    """
    View which is the homepage of the website. It shows the x latest recipes where x is
    MAX_LATEST_RECIPES in settings
    :param request:
    :return:
    """
    latest_recipes = Recipe.objects.filter(published=True).order_by('-published_at')[:settings.MAX_LATEST_RECIPES]
    return render(request, 'recipes/recipes_homepage.html', {
        'latest_recipes': latest_recipes,
    })


def recipe_details(request, recipe_slug):
    """
    View to display details page for a recipe
    :param request:
    :param recipe_slug: The slug of the recipe
    :return:
    """
    recipe = get_object_or_404(Recipe, slug=recipe_slug, published=True)
    comments = recipe.comments.order_by('-created_at').all()
    num_page = 1
    if 'num_page' in request.GET:
        num_page = request.GET['num_page']
    paginator = Paginator(comments, settings.MAX_COMMENT_PAGE)
    recipe_rate = None
    if request.user.is_authenticated:
        recipe_rate = RecipeRate.objects.filter(recipe=recipe, user=request.user).first()
    rate_form = recipeforms.RecipeRateForm(instance=recipe_rate)
    comment_form = recipeforms.RecipeCommentForm()
    return render(request, 'recipes/recipes_details.html',
                  {
                      'recipe': recipe,
                      'comment_paginator': paginator.page(num_page),
                      'range_page': range(1, paginator.num_pages + 1),
                      'comment_form': comment_form,
                      'rate_form': rate_form,
                      'user': request.user
                  })


def recipe_search(request):
    """
    View to search a recipe based on a keyword (see handle_search method at the bottom of this file)
    :param request:
    :return:
    """
    return handle_search(request, Recipe.objects.filter(published=True), 'recipes/recipe_search.html', True)


def recipe_browse_all(request):
    """
    View to browse recipes globally
    :param request:
    :return:
    """
    return handle_search(request, Recipe.objects.filter(published=True),
                         'recipes/recipe_browse.html', False,
                         {'mode': 'all', })


def recipe_browse_category(request, category_slug):
    """
    View to browse recipes by categories (see handle_search method at the bottom of this file)
    :param request:
    :param category_slug: The name of the category
    :return:
    """
    category = get_object_or_404(RecipeType, slug=category_slug)
    return handle_search(request, Recipe.objects.filter(recipe_type=category, published=True),
                         'recipes/recipe_browse.html', False,
                         {'mode': 'category', 'category_slug': category_slug, 'category_name': category.name})


def recipe_browse_skill(request, skill_slug):
    """
    View to browse recipes by skill needed / difficulty (see handle_search method at the bottom of this file)
    :param request:
    :param skill_slug: The name of the skill
    :return:
    """
    skill = get_object_or_404(RecipeSkill, slug=skill_slug)
    return handle_search(request, Recipe.objects.filter(recipe_skill=skill, published=True),
                         'recipes/recipe_browse.html', False,
                         {'mode': 'skill', 'skill_slug': skill_slug, 'skill_name': skill.name})


@login_required(login_url="accounts:login")
def recipe_create(request):
    """
    View to create a recipe
    :param request:
    :return:
    """
    if request.method == 'POST':
        recipe_form = recipeforms.RecipeCreateForm(request.POST, request.FILES)
        cost_form = recipeforms.RecipeCostForm(request.POST)
        if recipe_form.is_valid() and cost_form.is_valid():
            # save recipe to db
            recipe = recipe_form.save(commit=False)
            recipe.slug = slugify(recipe.name)
            recipe_cost = cost_form.save()
            recipe.name = recipe.name.title()
            recipe.recipe_cost = recipe_cost
            recipe.author = request.user
            recipe.save()
            return handle_next(request, redirect('recipes:edit', recipe_slug=recipe.slug))
    else:
        recipe_form = recipeforms.RecipeCreateForm()
        cost_form = recipeforms.RecipeCostForm()
    return render(request, 'recipes/recipes_create.html',
                  {
                      'recipe_create_form': recipe_form,
                      'recipe_cost_form': cost_form
                  })


@login_required(login_url="accounts:login")
def recipe_edit(request, recipe_slug):
    """
    View to edit a recipe
    :param request:
    :param recipe_slug: The slug of the recipe
    :return:
    """
    recipe = get_object_or_404(Recipe, slug=recipe_slug)
    if recipe.author == request.user:
        image_form = recipeforms.RecipeImageForm()
        step_form = recipeforms.RecipeStepForm()
        ingred_form = recipeforms.RecipeIngredientForm()
        if request.method == 'POST':
            edit_form = recipeforms.RecipeEditForm(request.POST, request.FILES, instance=recipe)
            cost_form = recipeforms.RecipeCostForm(request.POST, instance=recipe.recipe_cost)
            if edit_form.is_valid() and cost_form.is_valid():
                # save recipe to db
                recipe = edit_form.save(commit=False)
                recipe.updated_at = datetime.now()
                recipe.save()
                cost_form.save()
                messages.success(request, _("Recipe updated successfully"))
                return handle_next(request, redirect('recipes:edit', recipe_slug=recipe.slug))
        else:
            edit_form = recipeforms.RecipeEditForm(instance=recipe)
            cost_form = recipeforms.RecipeCostForm(instance=recipe.recipe_cost)
    else:
        messages.error(request, _("You're not the author of this recipe"))
        return redirect('recipes:homepage')
    return render(request, 'recipes/recipe_edit.html',
                  {
                      'edit_recipe_form': edit_form,
                      'cost_form': cost_form,
                      'image_form': image_form,
                      'step_form': step_form,
                      'ingred_form': ingred_form,
                      'recipe': recipe
                  })


@login_required(login_url="accounts:login")
def recipe_delete(request, recipe_pk):
    """
    View to delete a recipe based on his primary key
    :param request:
    :param recipe_pk: The primary key of the recipe
    :return:
    """
    recipe = get_object_or_404(Recipe, pk=recipe_pk)
    if recipe.author == request.user:
        recipe.delete()
        messages.success(request, _('The recipe was deleted successfully'))
    else:
        messages.error(request, _("You're not the author of this recipe"))
    return handle_next(request, redirect('recipes:homepage'))


@login_required(login_url="accounts:login")
def recipe_add_image(request, recipe_pk):
    """
    View to add an additional image to a recipe. A limit exists for the number of images (see
    MAX_RECIPE_IMAGES in settings)
    :param request:
    :param recipe_pk: The primary key of the recipe
    :return:
    """
    if request.method == 'POST':
        recipe = get_object_or_404(Recipe, pk=recipe_pk)
        if recipe.author == request.user:
            if recipe.images.count() < settings.MAX_RECIPE_IMAGES:
                image_form = recipeforms.RecipeImageForm(request.POST, request.FILES)
                if image_form.is_valid():
                    recipe_image = image_form.save(commit=False)
                    recipe_image.recipe = recipe
                    recipe_image.save()
                    recipe.updated_at = datetime.now()
                    recipe.save()
                    messages.success(request, _('The image was added successfully'))
                return handle_next(request, redirect('recipes:edit', recipe_slug=recipe.slug))
            else:
                messages.error(request, _("The maximum number of images by recipes has been exceeded"))
        else:
            messages.error(request, _("You're not the author of this recipe"))
    return redirect('recipes:homepage')


@login_required(login_url="accounts:login")
def recipe_add_step(request, recipe_pk):
    """
    View to add a step. The order value is equal to the count step of the recipe + 1
    :param request:
    :param recipe_pk: Primary key of the recipe
    :return:
    """
    if request.method == 'POST':
        recipe = get_object_or_404(Recipe, pk=recipe_pk)
        if recipe.author == request.user:
            step_form = recipeforms.RecipeStepForm(request.POST)
            if step_form.is_valid():
                recipe_step = step_form.save(commit=False)
                recipe_step.order = recipe.steps.count() + 1
                recipe_step.recipe = recipe
                recipe_step.save()
                recipe.updated_at = datetime.now()
                recipe.save()
                messages.success(request, _('The step was added successfully'))
            return handle_next(request, redirect('recipes:edit', recipe_slug=recipe.slug))
        else:
            messages.error(request, _("You're not the author of this recipe"))
    return redirect('recipes:homepage')


@login_required(login_url="accounts:login")
def recipe_delete_step(request, step_pk):
    """

recipes/templates/recipes/recipe_browse.html
{% extends 'base_layout.html' %}

{% load static from staticfiles %}
{% load i18n %}

{% block title %}
    {% trans "Browse Recipes" %}
{% endblock %}

{% block banner %}
    <div class="banner1">
        <div class="container">
        </div>
    </div>
{% endblock %}

{% block content %}
    {% if mode == 'category' %}
        <h1 class="wow fadeInLeftBig" data-wow-duration="1000ms" data-wow-delay="300ms">{% trans "Browse Category" %}
            "{{ category_name }}"
            ({{ number_results }} {% trans "Results" %})</h1>
    {% elif mode == 'skill' %}
        <h1 class="wow fadeInLeftBig" data-wow-duration="1000ms" data-wow-delay="300ms">{% trans "Browse Skill" %}
            "{{ skill_name }}"
            ({{ number_results }} {% trans "Results" %})</h1>
    {% elif mode == 'all' %}
        <h1 class="wow fadeInLeftBig" data-wow-duration="1000ms" data-wow-delay="300ms">{% trans "Browse All" %}
            ({{ number_results }} {% trans "Results" %})</h1>
    {% endif %}
    <br>
    <div style="float:right">
        <form class="form-inline" role="search">
            <div class="form-group">
                <label>{{ filterform.keyword.label }}</label>
                {{ filterform.keyword }}
            </div>
            <div class="form-group">
                <label>{{ filterform.filter.label }}</label>
                {{ filterform.filter }}
            </div>
            <div class="form-group">
                <label>{{ filterform.order.label }}</label>
                {{ filterform.order }}
            </div>
            <button class="btn btn-default btn-md" type="submit">Filtrer</button>
        </form>
    </div>
    <div class="event-grids">
        {% if number_results > 0 %}
            {% for recipe in results_paginator.object_list %}
                <div class="col-md-4 event-grid wow flipInY recipe-list" data-wow-duration="1000ms"
                     data-wow-delay="300ms">
                    <p class="dte">{{ recipe.created_at }}
                        <input type="text"
                               value="{{ recipe.get_median_rate }}"
                               min="0" step="0.5" data-size="xs"
                               class="rating-disabled">
                        {% if recipe.rates.count > 0 %}
                            {{ recipe.rates.count }} ratings
                        {% else %}
                            {% trans "Not yet rated" %}
                        {% endif %}
                        ({{ recipe.comments.count }} {% trans "Comments" %})
                    </p>
                    <img src="{{ recipe.thumbnail.url }}" alt=" " class="recipe-thumbnail"/>
                    <div class="nobis">
                        <a href="{% url 'recipes:details' recipe_slug=recipe.slug %}">{{ recipe.name }}<span>{% trans "By" %} {{ recipe.author.first_name }} {{ recipe.author.last_name }}</span></a>
                    </div>
                    <p class="quod">{{ recipe.get_short_description }}</p>
                    <div class="more">
                        <a href="{% url 'recipes:details' recipe_slug=recipe.slug %}"
                           class="hvr-curl-bottom-right">{% trans "Read More..." %}</a>
                    </div>
                </div>
            {% endfor %}
            <div class="clearfix"></div>
            <br>
            {% if mode == 'category' %}
                {% url 'recipes:browse_category' category_slug=category_slug as base_url %}
            {% elif mode == 'skill' %}
                {% url 'recipes:browse_skill' skill_slug=skill_slug as base_url %}
            {% elif mode == 'all' %}
                {% url 'recipes:browse_all' as base_url %}
            {% endif %}
            {% with base_url|add:'?keyword='|add:keyword|add:'&filter='|add:filter|add:'&order='|add:order as full_url %}
                {% include 'utils/_pagination.html' with paginator=results_paginator base_url=full_url %}
            {% endwith %}
        {% else %}
            <br>
            <div class="alert alert-info" role="alert">
                <strong>{% trans "Sorry, we have no results for this research :(" %}</strong>
            </div>
        {% endif %}
    </div>
{% endblock %}

recipes/templates/recipes/recipe_edit.html
{% extends 'base_layout.html' %}

{% load static from staticfiles %}
{% load i18n %}

{% block title %}
    {% trans "Edit Recipe" %}
{% endblock %}

{% block banner %}
    <div class="banner1">
        <div class="container">
        </div>
    </div>
{% endblock %}

{% block content %}
    <h1 class="title wow fadeInLeftBig" data-wow-duration="1000ms" data-wow-delay="300ms">{% trans 'Edit Recipe' %}
        "{{ recipe.name }}"</h1>
    <br>
    {% if not recipe.published %}
        <div class="alert alert-warning">
            <strong>{% trans "This recipe is not published yet. To make it visible by other cookers, please click on this button" %}
                <a class="btn btn-warning btn-md"
                   href="{% url 'recipes:publish_toogle' recipe_pk=recipe.pk %}">Publish</a></strong>
        </div>
    {% endif %}

    <img src="{{ recipe.thumbnail.url }}"/>
    <br><br>
    <div class="wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">

        {% include 'recipes/forms/_form_edit_recipe.html' with recipe=recipe edit_recipe_form=edit_recipe_form cost_form=cost_form %}

        {% include 'recipes/parts/_show_edit_image.html' with recipe=recipe %}

        {% if recipe.can_add_images %}
            {% include 'recipes/forms/_form_add_image.html' with image_form=image_form %}
        {% else %}
            <div class="alert alert-warning">
                <strong>{% trans "Sorry, you can't add more photos to this recipe :(" %}</strong>
            </div>
        {% endif %}

        {% include 'recipes/parts/_show_edit_ingredient.html' with recipe=recipe %}

        {% include 'recipes/forms/_form_add_ingredient.html' with ingred_form=ingred_form %}

        {% include 'recipes/parts/_show_edit_step.html' with recipe=recipe %}

        {% include 'recipes/forms/_form_add_step.html' with step_form=step_form %}

    </div>

    {% include 'utils/_modal_confirmation.html' %}

{% endblock %}

recipes/templates/recipes/recipe_search.html
{% extends 'base_layout.html' %}

{% load static from staticfiles %}
{% load i18n %}

{% block title %}
    {% trans "Search Recipe" %}
{% endblock %}

{% block banner %}
    <div class="banner1">
        <div class="container">
        </div>
    </div>
{% endblock %}

{% block content %}
    <h1 class="wow fadeInLeftBig" data-wow-duration="1000ms" data-wow-delay="300ms">{% trans "Search results" %}
        ({{ number_results }} {% trans "Results" %})</h1>
    <br>
    <div style="float:right">
        <form class="form-inline" role="search">
            <div class="form-group">
                <label>{{ filterform.keyword.label }}</label>
                {{ filterform.keyword }}
            </div>
            <div class="form-group">
                <label>{{ filterform.filter.label }}</label>
                {{ filterform.filter }}
            </div>
            <div class="form-group">
                <label>{{ filterform.order.label }}</label>
                {{ filterform.order }}
            </div>
            <button class="btn btn-default btn-md" type="submit">Filtrer</button>
        </form>
    </div>
    <div class="event-grids">
        {% if number_results > 0 %}
            {% for recipe in results_paginator.object_list %}
                <div class="col-md-4 event-grid wow flipInY recipe-list" data-wow-duration="1000ms"
                     data-wow-delay="300ms">
                    <p class="dte">{{ recipe.created_at }}
                        <input type="text"
                               value="{{ recipe.get_median_rate }}"
                               min="0" step="0.5" data-size="xs"
                               class="rating-disabled">
                        {% if recipe.rates.count > 0 %}
                            {{ recipe.rates.count }} ratings
                        {% else %}
                            {% trans "Not yet rated" %}
                        {% endif %}
                    </p>
                    <img src="{{ recipe.thumbnail.url }}" alt=" " class="recipe-thumbnail"/>
                    <div class="nobis">
                        <a href="{% url 'recipes:details' recipe_slug=recipe.slug %}">{{ recipe.name }}<span>{% trans "By" %} {{ recipe.author.first_name }} {{ recipe.author.last_name }}</span></a>
                    </div>
                    <p class="quod">{{ recipe.get_short_description }}</p>
                    <div class="more">
                        <a href="{% url 'recipes:details' recipe_slug=recipe.slug %}"
                           class="hvr-curl-bottom-right">{% trans "Read More..." %}</a>
                    </div>
                </div>
            {% endfor %}
            <div class="clearfix"></div>
            <br>
            {% url 'recipes:search' as search_url %}
            {% with search_url|add:'?keyword='|add:keyword|add:'&filter='|add:filter|add:'&order='|add:order as full_url %}
                {% include 'utils/_pagination.html' with paginator=results_paginator base_url=full_url %}
            {% endwith %}
        {% else %}
            <br>
            <div class="alert alert-info" role="alert">
                <strong>{% trans "Sorry, we have no results for this research :(" %}</strong>
            </div>
        {% endif %}
    </div>
{% endblock %}

recipes/templates/recipes/recipes_create.html
{% extends 'base_layout.html' %}

{% load static from staticfiles %}
{% load i18n %}

{% block title %}
    {% trans "Create Recipe" %}
{% endblock %}

{% block banner %}
    <div class="banner1">
        <div class="container">
        </div>
    </div>
{% endblock %}

{% block content %}

    <h1 class="title wow fadeInLeftBig" data-wow-duration="1000ms" data-wow-delay="300ms">{% trans 'Create New Recipe' %}</h1>
    <br>
    <div class="wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
        <form class="site-form" action="{% url 'recipes:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ recipe_create_form.as_p }}
            {{ recipe_cost_form.as_p }}
            <br>
            <button type="submit" class="btn btn-default btn-lg">Create</button>
        </form>
    </div>

{% endblock %}

recipes/templates/recipes/recipes_details.html
{% extends 'base_layout.html' %}

{% load static from staticfiles %}
{% load i18n %}

{% block title %}
    {% trans "Details of Recipe" %} {{ recipe.name }}
{% endblock %}

{% block banner %}
    <div class="banner1">
        <div class="container">
        </div>
    </div>
{% endblock %}

{% block content %}

    <h1 class="animated fadeInLeftBig" data-wow-duration="1000ms" data-wow-delay="300ms">
        {{ recipe.name }}
        <div class="flag flag--{{ recipe.recipe_origin.css_class }}" style="width:1em;height:0.7em;"></div>
        - {{ recipe.recipe_type.name }}
    </h1>

    <div class="single-left wow fadeInLeftBig" data-wow-duration="1000ms" data-wow-delay="300ms">
        {% if user.is_authenticated and user == recipe.author %}
            <button type="button" class="btn btn-danger btn-md btn-confirm"
                    data-title="{% trans "Delete Recipe ?" %}"
                    data-message="{% trans "Are you sure that you want to delete this recipe ?" %}"
                    data-action="{% url 'recipes:delete' recipe_pk=recipe.pk %}">{% trans "Delete" %} <i
                    class="fas fa-trash-alt fa-lg"></i></button>
            <a href="{% url 'recipes:edit' recipe_slug=recipe.slug %}"
               class="btn btn-warning btn-md">{% trans "Edit" %} <i class="fas fa-edit fa-lg"></i></a>
        {% endif %}
        <p>{% trans "Created On" %} <span>{{ recipe.created_at }} {% trans "By" %} <a
                href="{% url 'accounts:view_profile' username=recipe.author.username %}">{{ recipe.author.username }}</a></span>
            <input type="text"
                   value="{{ recipe.get_median_rate }}"
                   data-size="xs"
                   class="rating-disabled">
            {% if recipe.rates.count > 0 %}
                {% trans "Median rate based on" %} {{ recipe.rates.count }} ratings
            {% else %}
                {% trans "Not yet rated" %}
            {% endif %}
        </p>

        <!-- Rate Form !-->
        {% if user.is_authenticated %}
            {% include 'recipes/forms/_form_rate.html' with recipe=recipe rate_form=rate_form %}
        {% else %}
            <a href="{% url 'accounts:login' %}">{% trans "You must be logged to rate a recipe" %}</a>
        {% endif %}

        <img src="{{ recipe.thumbnail.url }}" alt=" " class="img-responsive"/>
    </div>

    <!-- General informations -->
    {% include 'recipes/parts/_recipe_meta_informations.html' with recipe=recipe %}

    <div class="clearfix"></div>

    <!-- Preparation informations -->
    {% include 'recipes/parts/_recipes_prep_informations.html' with recipe=recipe %}

    <!-- Leave Comment !-->
    {% if user.is_authenticated %}
        {% include 'recipes/forms/_form_leave_comment.html' with recipe=recipe comment_form=comment_form %}
    {% else %}
        <a href="{% url 'accounts:login' %}">{% trans "You must be logged to post a comment." %}</a>
    {% endif %}

    <!-- Comment List -->
    {% if recipe.comments.count > 0 %}
        {% include 'recipes/parts/_comments_list.html' with recipe=recipe comment_paginator=comment_paginator %}
        {% url 'recipes:details' recipe_slug=recipe.slug as detail_url %}
        {% include 'utils/_pagination.html' with paginator=comment_paginator base_url=detail_url|add:'?' %}
    {% else %}
        <br>
        <div class="alert alert-info">
            <strong>{% trans "This recipe has no comments yet :(" %}</strong>
        </div>
    {% endif %}

    {% include 'utils/_modal_confirmation.html' %}

{% endblock %}

recipes/templates/recipes/recipes_homepage.html
{% extends 'base_layout.html' %}

{% load static from staticfiles %}
{% load i18n %}

{% block title %}
    {% trans "Home" %}
{% endblock %}

{% block banner %}
    <!-- banner -->
    <div class="banner">
        <div class="container">
            <div class="banner-info" style="margin-top:50px;">
                <h1 class="animated fadeInLeftBig" data-wow-duration="1000ms"
                    data-wow-delay="300ms">{% trans "Welcome on MasterCook" %}<span>{% trans "The community to share recipes across the world" %}</span>
                </h1>
                <h2 style="font-size:50px;">{% trans "Latest Recipes" %}</h2>
                <div class="banner-info1 animated wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                    <ul id="flexiselDemo1">
                        {% for recipe in latest_recipes %}
                            <li>
                                <div class="banner-info1-grid">
                                    <a href="{% url 'recipes:details' recipe_slug=recipe.slug %}"><img
                                            src="{{ recipe.thumbnail.url }}" alt="" class="img-responsive" style="width:250px;height:200px;"/></a>
                                    <h3>
                                        {{ recipe.name }}
                                    </h3>
                                    <p>{{ recipe.get_short_description }}</p>
                                    <a class="btn btn-default btn-md"
                                       href="{% url 'recipes:details' recipe_slug=recipe.slug %}">{% trans "Read More" %}</a>
                                    <div class="more wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                    <script type="text/javascript">
                        $(window).load(function () {
                            $("#flexiselDemo1").flexisel({
                                visibleItems: 3,
                                animationSpeed: 1000,
                                autoPlay: true,
                                autoPlaySpeed: 3000,
                                pauseOnHover: true,
                                enableResponsiveBreakpoints: true,
                                responsiveBreakpoints: {
                                    portrait: {
                                        changePoint: 480,
                                        visibleItems: 1
                                    },
                                    landscape: {
                                        changePoint: 640,
                                        visibleItems: 2
                                    },
                                    tablet: {
                                        changePoint: 768,
                                        visibleItems: 2
                                    }
                                }
                            });

                        });
                    </script>
                    <script type="text/javascript" src="{% static 'js/jquery.flexisel.js' %}"></script>
                </div>
            </div>
        </div>
    </div>
    <!-- //banner -->
{% endblock %}

recipes/templates/recipes/recipes_reply_to_comment.html
{% extends 'base_layout.html' %}

{% load static from staticfiles %}
{% load i18n %}

{% block title %}
    {% trans "Reply to comment of" %} {{ comment.user.username }}
{% endblock %}

{% block banner %}
    <div class="banner1">
        <div class="container">
        </div>
    </div>
{% endblock %}

{% block content %}

    <div class="leave-comment wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
        <h3>{% trans "Reply to comment of" %} {{ comment.user.username }}</h3>
        <form class="site-form" action="{% url 'recipes:reply_to_comment' comment_pk=comment.pk %}" method="post">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <button type="submit" class="btn btn-default btn-lg">{% trans "Reply" %}</button>
        </form>
    </div>

{% endblock %}