accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profiles/<str:username>/', views.profile_view, name='view_profile'),
    path('profile/edit/', views.update_profile_view, name='edit_profile'),
    path('password/edit/', views.update_password_view, name='edit_password'),
    path('mydashboard/', views.user_dashboard_view, name='my_dashboard'),
]

mastercook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('shortcodes/', views.shortcodes)
]

"""
urlpatterns += i18n_patterns(
    path('generic/', include('generic.urls')),
    path('', include('recipes.urls')),
    path('accounts/', include('accounts.urls'))
)
"""

urlpatterns += [
    path('', views.root_redirect),
    path('utils/', include('utils.urls')),
    path('recipes/', include('recipes.urls')),
    path('accounts/', include('accounts.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.recipe_homepage, name='homepage'),
    path('create', views.recipe_create, name='create'),
    path('delete/<int:recipe_pk>', views.recipe_delete, name='delete'),
    path('<slug:recipe_slug>/edit', views.recipe_edit, name='edit'),
    path('<int:recipe_pk>/publish_toogle', views.recipe_toogle_publish, name='publish_toogle'),
    path('<int:recipe_pk>/comment/add', views.recipe_add_comment, name='add_comment'),
    path('<int:recipe_pk>/image/add', views.recipe_add_image, name='add_image'),
    path('image/delete/<int:image_pk>', views.recipe_delete_image, name='delete_image'),
    path('<int:recipe_pk>/step/add', views.recipe_add_step, name='add_step'),
    path('step/up/<int:step_pk>', views.recipe_up_step, name='up_step'),
    path('step/down/<int:step_pk>', views.recipe_down_step, name='down_step'),
    path('step/delete/<int:step_pk>', views.recipe_delete_step, name='delete_step'),
    path('<int:recipe_pk>/ingredient/add', views.recipe_add_ingredient, name='add_ingredient'),
    path('ingredient/delete/<int:ingredient_pk>', views.recipe_delete_ingredient, name='delete_ingredient'),
    path('<int:recipe_pk>/rate/add', views.recipe_add_rate, name='add_rate'),
    path('<slug:recipe_slug>/details', views.recipe_details, name='details'),
    path('comment/<int:comment_pk>/replyto', views.recipe_reply_comment, name='reply_to_comment'),
    path('search', views.recipe_search, name='search'),
    path('browse/all', views.recipe_browse_all, name='browse_all'),
    path('browse/category/<slug:category_slug>', views.recipe_browse_category, name='browse_category'),
    path('browse/skill/<slug:skill_slug>', views.recipe_browse_skill, name='browse_skill')
]

utils/urls.py
from django.urls import path
from . import views

app_name = 'utils'

urlpatterns = [
    path('changueLocale/<str:user_language>', views.switch_lang_view, name='switch_language'),
]

recipes/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.utils.translation import ugettext_lazy as _
from .models import Recipe, RecipeType, RecipeSkill, RecipeComment, RecipeRate, RecipeIngredient, RecipeStep, \
    RecipeImage
from . import forms as recipeforms
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from slugify import slugify
from datetime import datetime
from django.core.paginator import Paginator
from django.conf import settings
from django.db.models import Avg, Q


# Create your views here.

def recipe_homepage(request):
    """
    View which is the homepage of the website. It shows the x latest recipes where x is
    MAX_LATEST_RECIPES in settings
    :param request:
    :return:
    """
    latest_recipes = Recipe.objects.filter(published=True).order_by('-published_at')[:settings.MAX_LATEST_RECIPES]
    return render(request, 'recipes/recipes_homepage.html', {
        'latest_recipes': latest_recipes,
    })


def recipe_details(request, recipe_slug):
    """
    View to display details page for a recipe
    :param request:
    :param recipe_slug: The slug of the recipe
    :return:
    """
    recipe = get_object_or_404(Recipe, slug=recipe_slug, published=True)
    comments = recipe.comments.order_by('-created_at').all()
    num_page = 1
    if 'num_page' in request.GET:
        num_page = request.GET['num_page']
    paginator = Paginator(comments, settings.MAX_COMMENT_PAGE)
    recipe_rate = None
    if request.user.is_authenticated:
        recipe_rate = RecipeRate.objects.filter(recipe=recipe, user=request.user).first()
    rate_form = recipeforms.RecipeRateForm(instance=recipe_rate)
    comment_form = recipeforms.RecipeCommentForm()
    return render(request, 'recipes/recipes_details.html',
                  {
                      'recipe': recipe,
                      'comment_paginator': paginator.page(num_page),
                      'range_page': range(1, paginator.num_pages + 1),
                      'comment_form': comment_form,
                      'rate_form': rate_form,
                      'user': request.user
                  })


def recipe_search(request):
    """
    View to search a recipe based on a keyword (see handle_search method at the bottom of this file)
    :param request:
    :return:
    """
    return handle_search(request, Recipe.objects.filter(published=True), 'recipes/recipe_search.html', True)


def recipe_browse_all(request):
    """
    View to browse recipes globally
    :param request:
    :return:
    """
    return handle_search(request, Recipe.objects.filter(published=True),
                         'recipes/recipe_browse.html', False,
                         {'mode': 'all', })


def recipe_browse_category(request, category_slug):
    """
    View to browse recipes by categories (see handle_search method at the bottom of this file)
    :param request:
    :param category_slug: The name of the category
    :return:
    """
    category = get_object_or_404(RecipeType, slug=category_slug)
    return handle_search(request, Recipe.objects.filter(recipe_type=category, published=True),
                         'recipes/recipe_browse.html', False,
                         {'mode': 'category', 'category_slug': category_slug, 'category_name': category.name})


def recipe_browse_skill(request, skill_slug):
    """
    View to browse recipes by skill needed / difficulty (see handle_search method at the bottom of this file)
    :param request:
    :param skill_slug: The name of the skill
    :return:
    """
    skill = get_object_or_404(RecipeSkill, slug=skill_slug)
    return handle_search(request, Recipe.objects.filter(recipe_skill=skill, published=True),
                         'recipes/recipe_browse.html', False,
                         {'mode': 'skill', 'skill_slug': skill_slug, 'skill_name': skill.name})


@login_required(login_url="accounts:login")
def recipe_create(request):
    """
    View to create a recipe
    :param request:
    :return:
    """
    if request.method == 'POST':
        recipe_form = recipeforms.RecipeCreateForm(request.POST, request.FILES)
        cost_form = recipeforms.RecipeCostForm(request.POST)
        if recipe_form.is_valid() and cost_form.is_valid():
            # save recipe to db
            recipe = recipe_form.save(commit=False)
            recipe.slug = slugify(recipe.name)
            recipe_cost = cost_form.save()
            recipe.name = recipe.name.title()
            recipe.recipe_cost = recipe_cost
            recipe.author = request.user
            recipe.save()
            return handle_next(request, redirect('recipes:edit', recipe_slug=recipe.slug))
    else:
        recipe_form = recipeforms.RecipeCreateForm()
        cost_form = recipeforms.RecipeCostForm()
    return render(request, 'recipes/recipes_create.html',
                  {
                      'recipe_create_form': recipe_form,
                      'recipe_cost_form': cost_form
                  })


@login_required(login_url="accounts:login")
def recipe_edit(request, recipe_slug):
    """
    View to edit a recipe
    :param request:
    :param recipe_slug: The slug of the recipe
    :return:
    """
    recipe = get_object_or_404(Recipe, slug=recipe_slug)
    if recipe.author == request.user:
        image_form = recipeforms.RecipeImageForm()
        step_form = recipeforms.RecipeStepForm()
        ingred_form = recipeforms.RecipeIngredientForm()
        if request.method == 'POST':
            edit_form = recipeforms.RecipeEditForm(request.POST, request.FILES, instance=recipe)
            cost_form = recipeforms.RecipeCostForm(request.POST, instance=recipe.recipe_cost)
            if edit_form.is_valid() and cost_form.is_valid():
                # save recipe to db
                recipe = edit_form.save(commit=False)
                recipe.updated_at = datetime.now()
                recipe.save()
                cost_form.save()
                messages.success(request, _("Recipe updated successfully"))
                return handle_next(request, redirect('recipes:edit', recipe_slug=recipe.slug))
        else:
            edit_form = recipeforms.RecipeEditForm(instance=recipe)
            cost_form = recipeforms.RecipeCostForm(instance=recipe.recipe_cost)
    else:
        messages.error(request, _("You're not the author of this recipe"))
        return redirect('recipes:homepage')
    return render(request, 'recipes/recipe_edit.html',
                  {
                      'edit_recipe_form': edit_form,
                      'cost_form': cost_form,
                      'image_form': image_form,
                      'step_form': step_form,
                      'ingred_form': ingred_form,
                      'recipe': recipe
                  })


@login_required(login_url="accounts:login")
def recipe_delete(request, recipe_pk):
    """
    View to delete a recipe based on his primary key
    :param request:
    :param recipe_pk: The primary key of the recipe
    :return:
    """
    recipe = get_object_or_404(Recipe, pk=recipe_pk)
    if recipe.author == request.user:
        recipe.delete()
        messages.success(request, _('The recipe was deleted successfully'))
    else:
        messages.error(request, _("You're not the author of this recipe"))
    return handle_next(request, redirect('recipes:homepage'))


@login_required(login_url="accounts:login")
def recipe_add_image(request, recipe_pk):
    """
    View to add an additional image to a recipe. A limit exists for the number of images (see
    MAX_RECIPE_IMAGES in settings)
    :param request:
    :param recipe_pk: The primary key of the recipe
    :return:
    """
    if request.method == 'POST':
        recipe = get_object_or_404(Recipe, pk=recipe_pk)
        if recipe.author == request.user:
            if recipe.images.count() < settings.MAX_RECIPE_IMAGES:
                image_form = recipeforms.RecipeImageForm(request.POST, request.FILES)
                if image_form.is_valid():
                    recipe_image = image_form.save(commit=False)
                    recipe_image.recipe = recipe
                    recipe_image.save()
                    recipe.updated_at = datetime.now()
                    recipe.save()
                    messages.success(request, _('The image was added successfully'))
                return handle_next(request, redirect('recipes:edit', recipe_slug=recipe.slug))
            else:
                messages.error(request, _("The maximum number of images by recipes has been exceeded"))
        else:
            messages.error(request, _("You're not the author of this recipe"))
    return redirect('recipes:homepage')


@login_required(login_url="accounts:login")
def recipe_add_step(request, recipe_pk):
    """
    View to add a step. The order value is equal to the count step of the recipe + 1
    :param request:
    :param recipe_pk: Primary key of the recipe
    :return:
    """
    if request.method == 'POST':
        recipe = get_object_or_404(Recipe, pk=recipe_pk)
        if recipe.author == request.user:
            step_form = recipeforms.RecipeStepForm(request.POST)
            if step_form.is_valid():
                recipe_step = step_form.save(commit=False)
                recipe_step.order = recipe.steps.count() + 1
                recipe_step.recipe = recipe
                recipe_step.save()
                recipe.updated_at = datetime.now()
                recipe.save()
                messages.success(request, _('The step was added successfully'))
            return handle_next(request, redirect('recipes:edit', recipe_slug=recipe.slug))
        else:
            messages.error(request, _("You're not the author of this recipe"))
    return redirect('recipes:homepage')


@login_required(login_url="accounts:login")
def recipe_delete_step(request, step_pk):
    """

recipes/templates/recipes/parts/_comments_list.html
{% load i18n %}

<div class="three-com" id="block-comment">
    <h3 class="wow fadeInUp" data-wow-duration="1000ms"
        data-wow-delay="300ms">{{ recipe.comments.count }} {% trans "Comments" %}
        <span>{% trans "on" %}</span>
        <label>{{ recipe.name }}</label>
    </h3>
    {% for comment in comment_paginator.object_list %}
        {% if comment.is_root %}
            <div class="tom-grid wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
                <div class="tom">
                    <img class="avatar" src="{{ comment.user.profile.avatar.url }}" alt=" "/>
                </div>
                <div class="tom-right">
                    <div class="Hardy">
                        <h4>
                            <a href="{% url 'accounts:view_profile' username=comment.user.username %}">
                                {{ comment.user.first_name }} {{ comment.user.last_name }}
                            </a>
                        </h4>
                        <p><label>{{ comment.created_at }}</label></p>
                    </div>
                    {% if user.is_authenticated %}
                        <div class="reply">
                            <a href="{% url 'recipes:reply_to_comment' comment_pk=comment.pk %}">Reply</a>
                        </div>
                    {% endif %}
                    <div class="clearfix"></div>
                    <p class="lorem">{{ comment.comment }}</p>
                </div>
                <div class="clearfix"></div>
            </div>
        {% endif %}
        {% for reply in comment.get_children %}
            <div class="tom-grid humour wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
                <div class="tom">
                    <img class="avatar" src="{{ reply.user.profile.avatar.url }}" alt=" "/>
                </div>
                <div class="tom-right">
                    <div class="Hardy">
                        <h4>
                            <a href="{% url 'accounts:view_profile' username=reply.user.username %}">
                                {{ reply.user.first_name }} {{ reply.user.last_name }}
                            </a>
                        </h4>
                        <p><label>{{ reply.created_at }}</label></p>
                    </div>
                    <div class="clearfix"></div>
                    <p class="lorem">{{ reply.comment }}</p>
                </div>
                <div class="clearfix"></div>
            </div>
        {% endfor %}
    {% endfor %}
</div>

recipes/templates/recipes/parts/_example_home.html
<!-- banner-bottom -->
<div class="banner-bottom">
    <div class="container">
        <div class="banner-bottom-grids">
            <div class="col-md-5 banner-bottom-grid wow fadeInRightBig" data-wow-duration="1000ms"
                 data-wow-delay="300ms">
                <h2>vel illum qui dolorem eum</h2>
                <p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem
                    accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae
                    ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt
                    explicabo.</p>
                <div class="more">
                    <a href="single.html" class="hvr-curl-bottom-right">Read More</a>
                </div>
            </div>
            <div class="col-md-7 banner-bottom-grid wow flipInY" data-wow-duration="1000ms" data-wow-delay="300ms">
                <div class="banner-bottom-grid1">
                    <img src="{% static 'images/1.jpg' %}" alt=" " class="img-responsive"/>
                    <div class="banner-bottom-grid-pos">
                        <div class="progress">
                            <div class="progress-bar" role="progressbar" aria-valuenow="30" aria-valuemin="0"
                                 aria-valuemax="100" style="width: 30%;">
                                <span class="sr-only">30% Complete</span>
                            </div>
                        </div>
                        <div class="progress progress1">
                            <div class="progress-bar" role="progressbar" aria-valuenow="20" aria-valuemin="0"
                                 aria-valuemax="100" style="width: 20%;">
                                <span class="sr-only">20% Complete</span>
                            </div>
                        </div>
                        <div class="progress progress2">
                            <div class="progress-bar" role="progressbar" aria-valuenow="30" aria-valuemin="0"
                                 aria-valuemax="100" style="width: 30%;">
                                <span class="sr-only">30% Complete</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="banner-bottom-grids">
            <div class="col-md-6 banner-bottom-grid-1 wow flipInY" data-wow-duration="1000ms"
                 data-wow-delay="300ms">
                <div class="banner-bottom-grid-11">
                    <img src="{% static 'images/2.jpg' %}" alt=" " class="img-responsive"/>
                    <div class="banner-bottom-grid-11-pos">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                            sed do eiusmod tempor incididunt ut labore et dolore magna
                            aliqua.Quis autem vel eum iure reprehenderit qui in ea voluptate
                            velit esse quam nihil molestiae consequatur.</p>
                        <div class="more m1">
                            <a href="single.html" class="hvr-curl-bottom-right">Read More</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 banner-bottom-grid-1 wow fadeInLeftBig" data-wow-duration="1500ms"
                 data-wow-delay="100ms">
                <h3>Excepteur sint occaecat cupidatat non proident</h3>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<!-- //banner-bottom -->
<!-- newsletter -->
<div class="newsletter">
    <div class="container">
        <div class="newsletter-info">
            <h3 class="wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">Newsletter</h3>
            <p class="wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">But who has any right to find
                fault with a man who chooses to enjoy
                a pleasure that has no annoying consequences</p>
            <form class="wow fadeInLeftBig" data-wow-duration="1000ms" data-wow-delay="300ms">
                <input type="mail" value="Enter Your Email" onfocus="this.value = '';"
                       onblur="if (this.value == '') {this.value = 'Enter Your Email';}" required="">
                <input type="submit" value="Send">
            </form>
        </div>
    </div>
</div>
<!-- //newsletter -->
<!-- newsletter-bottom -->
<div class="newsletter-bottom">
    <div class="container">
        <div class="newsletter-bottom-grids">
            <div class="col-md-6 newsletter-bottom-grid wow fadeInLeftBig" data-wow-duration="1000ms"
                 data-wow-delay="300ms">
                <h3>At vero eos et accusamus et iusto odio</h3>
                <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem
                    accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae
                    ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt
                    explicabo.</p>
                <div class="more">
                    <a href="single.html" class="hvr-curl-bottom-right">Read More</a>
                </div>
            </div>
            <div class="col-md-6 newsletter-bottom-grid wow flipInY" data-wow-duration="1000ms"
                 data-wow-delay="300ms">
                <img src="{% static 'images/4.jpg' %}" alt=" " class="img-responsive"/>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="newsletter-bottom-grids">
            <div class="col-md-6 newsletter-bottom-grid wow flipInY" data-wow-duration="1000ms"
                 data-wow-delay="300ms">
                <img src="{% static 'images/5.jpg' %}" alt=" " class="img-responsive"/>
            </div>
            <div class="col-md-6 newsletter-bottom-grid  wow fadeInLeftBig" data-wow-duration="1000ms"
                 data-wow-delay="300ms">
                <h3>At vero eos et accusamus et iusto odio</h3>
                <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem
                    accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae
                    ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt
                    explicabo.</p>
                <div class="more">
                    <a href="single.html" class="hvr-curl-bottom-right">Read More</a>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<!-- //newsletter-bottom -->

recipes/templates/recipes/parts/_recipe_meta_informations.html
{% load i18n %}

<div class="single-right wow fadeInRightBig" data-wow-duration="1000ms" data-wow-delay="300ms">
    <h2>{% trans "Level" %} : {{ recipe.recipe_skill.name }} - {% trans "Origin" %}
        : {{ recipe.recipe_origin.name }}</h2>
    <p> {% trans "Description" %} :
        <span>
            {{ recipe.description }}
            </span>
    </p>
    <br>
    <div class="col-lg-10 footer-grid wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
        <h3 style="color:black">{% trans "Other photos" %}</h3>
        {% if recipe.images.count > 0 %}
            {% for photo in recipe.images.all %}
                <div class="footer-grd">
                    <a href="{{ photo.image.url }}"><img src="{{ photo.image.url }}" class="img-responsive" alt=""/></a>
                </div>
            {% endfor %}
        {% else %}
            <div class="alert alert-info">
                <strong>{% trans "No additional photos for this recipe yet :(" %}</strong>
            </div>
        {% endif %}
        <div class="clearfix"></div>
    </div>
</div>

recipes/templates/recipes/parts/_recipes_prep_informations.html
{% load i18n %}

<div class="tags-cate">
    <div class="cat-grid wow flipInY" data-wow-duration="1000ms" data-wow-delay="300ms">
        <h4><span>T</span>ime <i class="fa fa-clock fa-lg"></i></h4>
        <ul>
            <li class="list-group-item">{% trans "Preparation time" %} {{ recipe.preparation_time }}</li>
            <li class="list-group-item">{% trans "Cooking time" %} {{ recipe.cooking_time }}</li>
            <li class="list-group-item">{% trans "Cooling time" %} {{ recipe.cooling_time }}</li>
        </ul>
    </div>
    <div class="cat-grid wow flipInY" data-wow-duration="1000ms" data-wow-delay="300ms">
        <h4><span>I</span>ngredients <i class="fas fa-utensils fa-lg"></i></h4>
        <ul class="list-group wow fadeInUp animated" data-wow-duration="1000ms" data-wow-delay="300ms"
            style="visibility: visible; animation-duration: 1000ms; animation-delay: 300ms; animation-name: fadeInUp;">
            {% if recipe.steps.count > 0 %}
                {% for ingredient in recipe.ingredients.all %}
                    <li class="list-group-item">
                        {{ ingredient.quantity }}{{ ingredient.unit_measure.symbol }}
                        - {{ ingredient.ingredient.name }}
                    </li>
                {% endfor %}
            {% else %}
                <li><a href="#">{% trans "No Ingredients yet" %}</a></li>
            {% endif %}
        </ul>
    </div>
    <div class="cat-grid wow flipInY" data-wow-duration="1000ms" data-wow-delay="300ms">
        <h4><span>S</span>teps <i class="fas fa-step-forward fa-lg"></i></h4>
        <ul>
            {% if recipe.steps.count > 0 %}
                {% for step in recipe.steps.all %}
                    <li class="list-group-item">{{ step.name }} - {{ step.description }}</li>
                {% endfor %}
            {% else %}
                <li><a href="#">{% trans "No steps yet" %}</a></li>
            {% endif %}
        </ul>
    </div>
    <div class="clearfix"></div>
</div>

recipes/templates/recipes/parts/_show_edit_image.html
{% load i18n %}

<h1>{% trans "Images" %}</h1>
<br>
<button class="btn btn-default btn-lg" data-toggle="collapse"
        data-target="#div_images">{% trans "Show/Edit Current Images" %}</button>
<div id="div_images" class="collapse">
    {% if recipe.images.count > 0 %}

        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>{% trans "Title" %}</th>
                <th>{% trans "Image" %}</th>
                <th>{% trans "Remove" %} ?</th>
            </tr>
            </thead>
            <tbody>
            {% for img in recipe.images.all %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ img.name }}</td>
                    <td><img src="{{ img.image.url }}" class="img-responsive" style="width:35%;height:50%;" alt=""/>
                    </td>
                    <td>
                        <button type="button" class="btn btn-danger btn-md btn-confirm"
                                data-title="{% trans "Delete Image ?" %}"
                                data-message="{% trans "Are you sure that you want to delete this image ?" %}"
                                data-action="{% url 'recipes:delete_image' image_pk=img.pk %}?next={% url 'recipes:edit' recipe_slug=recipe.slug %}">
                            {% trans "Delete" %}
                        </button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <br>
        <div class="alert alert-info">
            <strong>{% trans "No additional photos for this recipe yet :(" %}</strong>
        </div>
    {% endif %}
</div>
<br><br>

recipes/templates/recipes/parts/_show_edit_ingredient.html
{% load i18n %}

<h1>{% trans "Ingredients" %}</h1>
<br>
<button class="btn btn-default btn-lg" data-toggle="collapse"
        data-target="#div_ingredients">{% trans "Show/Edit Current Ingredients" %}</button>
<div id="div_ingredients" class="collapse">
    {% if recipe.ingredients.count > 0 %}
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>{% trans "Type" %}</th>
                <th>{% trans "Name" %}</th>
                <th>{% trans "Quantity" %} ?</th>
                <th>{% trans "Remove" %} ?</th>
            </tr>
            </thead>
            <tbody>
            {% for ingred in recipe.ingredients.all %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ ingred.ingredient.ingredient_type.name }}</td>
                    <td>{{ ingred.ingredient.name }}</td>
                    <td>{{ ingred.quantity }} {{ ingred.unit_measure.symbol }}</td>
                    <td>
                        <button type="button" class="btn btn-danger btn-md btn-confirm"
                                data-title="{% trans "Delete Ingredient ?" %}"
                                data-message="{% trans "Are you sure that you want to delete this Ingredient ?" %}"
                                data-action="{% url 'recipes:delete_ingredient' ingredient_pk=ingred.pk %}?next={% url 'recipes:edit' recipe_slug=recipe.slug %}">
                            {% trans "Delete" %}
                        </button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <br>
        <div class="alert alert-info">
            <strong>{% trans "No ingredients for this recipe yet :(" %}</strong>
        </div>
    {% endif %}
</div>
<br><br>

recipes/templates/recipes/parts/_show_edit_step.html
{% load i18n %}

<h1>{% trans "Steps" %}</h1>
<br>
<button class="btn btn-default btn-lg" data-toggle="collapse"
        data-target="#div_steps">{% trans "Show/Edit Current Steps" %}</button>
<div id="div_steps" class="collapse">
    {% if recipe.steps.count > 0 %}
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>{% trans "Title" %}</th>
                <th>{% trans "Description" %}</th>
                <th>{% trans "Reorder" %} ?</th>
                <th>{% trans "Remove" %} ?</th>
            </tr>
            </thead>
            <tbody>
            {% for step in recipe.steps.all %}
                <tr>
                    <td>{{ step.order }}</td>
                    <td>{{ step.name }}</td>
                    <td>{{ step.get_short_description }}</td>
                    <td><a class="btn btn-info" href="{% url 'recipes:up_step' step_pk=step.pk %}"><i
                            class="fas fa-arrow-alt-circle-up"></i></a>
                        <a class="btn btn-warning" href="{% url 'recipes:down_step' step_pk=step.pk %}"><i
                                class="fas fa-arrow-alt-circle-down"></i></a></td>
                    <td>
                        <button type="button" class="btn btn-danger btn-md btn-confirm"
                                data-title="{% trans "Delete Step ?" %}"
                                data-message="{% trans "Are you sure that you want to delete this step ?" %}"
                                data-action="{% url 'recipes:delete_step' step_pk=step.pk %}?next={% url 'recipes:edit' recipe_slug=recipe.slug %}">
                            {% trans "Delete" %}
                        </button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <br>
        <div class="alert alert-info">
            <strong>{% trans "No steps for this recipe yet :(" %}</strong>
        </div>
    {% endif %}
</div>
<br><br>