accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profiles/<str:username>/', views.profile_view, name='view_profile'),
    path('profile/edit/', views.update_profile_view, name='edit_profile'),
    path('password/edit/', views.update_password_view, name='edit_password'),
    path('mydashboard/', views.user_dashboard_view, name='my_dashboard'),
]

mastercook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('shortcodes/', views.shortcodes)
]

"""
urlpatterns += i18n_patterns(
    path('generic/', include('generic.urls')),
    path('', include('recipes.urls')),
    path('accounts/', include('accounts.urls'))
)
"""

urlpatterns += [
    path('', views.root_redirect),
    path('utils/', include('utils.urls')),
    path('recipes/', include('recipes.urls')),
    path('accounts/', include('accounts.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.recipe_homepage, name='homepage'),
    path('create', views.recipe_create, name='create'),
    path('delete/<int:recipe_pk>', views.recipe_delete, name='delete'),
    path('<slug:recipe_slug>/edit', views.recipe_edit, name='edit'),
    path('<int:recipe_pk>/publish_toogle', views.recipe_toogle_publish, name='publish_toogle'),
    path('<int:recipe_pk>/comment/add', views.recipe_add_comment, name='add_comment'),
    path('<int:recipe_pk>/image/add', views.recipe_add_image, name='add_image'),
    path('image/delete/<int:image_pk>', views.recipe_delete_image, name='delete_image'),
    path('<int:recipe_pk>/step/add', views.recipe_add_step, name='add_step'),
    path('step/up/<int:step_pk>', views.recipe_up_step, name='up_step'),
    path('step/down/<int:step_pk>', views.recipe_down_step, name='down_step'),
    path('step/delete/<int:step_pk>', views.recipe_delete_step, name='delete_step'),
    path('<int:recipe_pk>/ingredient/add', views.recipe_add_ingredient, name='add_ingredient'),
    path('ingredient/delete/<int:ingredient_pk>', views.recipe_delete_ingredient, name='delete_ingredient'),
    path('<int:recipe_pk>/rate/add', views.recipe_add_rate, name='add_rate'),
    path('<slug:recipe_slug>/details', views.recipe_details, name='details'),
    path('comment/<int:comment_pk>/replyto', views.recipe_reply_comment, name='reply_to_comment'),
    path('search', views.recipe_search, name='search'),
    path('browse/all', views.recipe_browse_all, name='browse_all'),
    path('browse/category/<slug:category_slug>', views.recipe_browse_category, name='browse_category'),
    path('browse/skill/<slug:skill_slug>', views.recipe_browse_skill, name='browse_skill')
]

utils/urls.py
from django.urls import path
from . import views

app_name = 'utils'

urlpatterns = [
    path('changueLocale/<str:user_language>', views.switch_lang_view, name='switch_language'),
]

templates/parts/_footer.html
{% load static from staticfiles %}
{% load static i18n %}
{% load utils_tags %}

<!-- footer -->
<div class="footer">
    <div class="container">
        <div class="footer-grids">
            <div class="col-md-3 footer-grid wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
                <h3>{% trans "MasterCook" %}</h3>
                <div class="footer-grd-left">
                    <img src="{% static 'images/6.jpg' %}" class="img-responsive" alt=" "/>
                </div>
                <div class="footer-grd-left">
                    <p>{% trans "The community to share recipes across the world" %}</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="col-md-3 footer-grid wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
                <h3>{% trans "By Types" %}</h3>
                {% footer_category_menu %}
            </div>
            <div class="col-md-3 footer-grid wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
                <h3>{% trans "By Skills" %}</h3>
                {% footer_skill_menu %}
            </div>
            <div class="col-md-3 footer-grid wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
                <h3>Flickr Posts</h3>
                <div class="footer-grd">
                    <a href="#"><img src="{% static 'images/7.jpg' %}" class="img-responsive" alt=" "/></a>
                </div>
                <div class="footer-grd">
                    <a href="#"><img src="{% static 'images/8.jpg' %}" class="img-responsive" alt=" "/></a>
                </div>
                <div class="footer-grd">
                    <a href="#"><img src="{% static 'images/7.jpg' %}" class="img-responsive" alt=" "/></a>
                </div>
                <div class="clearfix"></div>
                <div class="footer-grd">
                    <a href="#"><img src="{% static 'images/8.jpg' %}" class="img-responsive" alt=" "/></a>
                </div>
                <div class="footer-grd">
                    <a href="#"><img src="{% static 'images/7.jpg' %}" class="img-responsive" alt=" "/></a>
                </div>
                <div class="footer-grd">
                    <a href="#"><img src="{% static 'images/8.jpg' %}" class="img-responsive" alt=" "/></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<div class="footer-bottom wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
    <div class="container">
        <p>&copy 2018 MasterCook. All rights reserved | Design by <a href="http://w3layouts.com/"> W3layouts.</a></p>
    </div>
</div>
<!-- //footer -->
<!-- for bootstrap working -->
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/star-rating.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

<!-- //js -->
<script src="{% static 'js/wow.min.js' %}"></script>
<script>
    new WOW().init();
</script>

templates/parts/_header.html
{% load static i18n %}
{% load utils_tags %}

<!-- header -->
<div class="header">
    <div class="container">
        <nav class="navbar navbar-default">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="logo">
                    <a class="navbar-brand" href="{% url 'recipes:homepage' %}">{% trans "MasterCook" %}</a>
                </div>
            </div>
            <div class="flag--france"></div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
                <nav class="cl-effect-13" id="cl-effect-13">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'recipes:homepage' %}" class="active">{% trans "Home" %}</a></li>
                        <li role="presentation" class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown"
                               href="#" role="button"
                               aria-haspopup="true" aria-expanded="false">{% trans "Browse" %} <span
                                    class="caret"></span></a>
                            {% advanced_search_menu %}

                        </li>
                        {% if user.is_authenticated %}
                            <li role="presentation" class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                                   aria-haspopup="true" aria-expanded="false">
                                    {% trans "My Profile" %} <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url 'accounts:edit_profile' %}"><i
                                            class="fas fa-eye fa-lg"></i> {% trans "Edit Profile" %}</a></li>
                                    <li><a href="{% url 'accounts:edit_password' %}"><i
                                            class="fas fa-key fa-lg"></i> {% trans "Modify Password" %}</a></li>
                                    <li><a href="{% url 'accounts:my_dashboard' %}"><i
                                            class="fas fa-clipboard-list fa-lg"></i> {% trans "My Dashboard" %}</a></li>
                                    <li><a href="{% url 'recipes:create' %}"><i
                                            class="fas fa-plus-circle fa-lg"></i> {% trans "New Recipe" %}</a>
                                    </li>
                                    <li><a href="{% url 'accounts:logout' %}"><i
                                            class="fas fa-sign-out-alt fa-lg"></i> {% trans "Logout" %}</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li><a href="{% url 'accounts:login' %}">{% trans "Login" %}</a></li>
                            <li><a href="{% url 'accounts:signup' %}">{% trans "Signup" %}</a></li>
                        {% endif %}
                        <li role="presentation" class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                               aria-haspopup="true" aria-expanded="false">
                                {% trans "Languages" %} <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                {% get_available_languages as LANGUAGES %}
                                {% get_language_info_list for LANGUAGES as languages %}
                                {% for language in languages %}
                                    <li>
                                        <a href="{% url 'utils:switch_language' user_language=language.code %}?next={{ request.path }}">
                                            <div class="flag--{{ language.code }}"></div>
                                        </a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                </nav>
                <div class="col-sm-3 col-md-3" style="margin-top:16px">
                    <form class="navbar-form" action="{% url "recipes:search" %}" role="search">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="{% trans "Search" %}" name="keyword">
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /.navbar-collapse -->
        </nav>
    </div>
</div>
<!-- header -->

templates/parts/_import_assets.html
{% load static from staticfiles %}

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta name="keywords" content="MasterCook Django Website Worlwide Recipe Community"/>
<script type="application/x-javascript"> addEventListener("load", function () {
    setTimeout(hideURLbar, 0);
}, false);

function hideURLbar() {
    window.scrollTo(0, 1);
} </script>
<!-- Custom Theme files -->
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all"/>
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all"/>
<link href="{% static 'css/star-rating.min.css' %}" rel="stylesheet" type="text/css" media="all"/>
<link href="{% static 'css/flags.css' %}" rel="stylesheet" type="text/css" media="all"/>
<link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css" media="all"/>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"
      integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
<!-- animation-effect -->
<link href="{% static 'css/animate.min.css' %}" rel="stylesheet">
<!-- //animation-effect -->
<link href='//fonts.googleapis.com/css?family=Alex+Brush' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Cabin:400,400italic,500,500italic,600,600italic,700,700italic'
      rel='stylesheet' type='text/css'>

<!-- js -->
<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>

templates/parts/_messages.html
<!-- Messages template to display success/error/info messages-->
{% if messages %}
    {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% else %}
                                   class="alert alert-info" {% endif %} role="alert">
        <h2>{{ message }}</h2>
    {% endfor %}
</div>
{% endif %}